language: cpp
os:
  - linux
  - osx
addons:
  apt:
    update: true
    sources:
    - llvm-toolchain-xenial-8
    packages:
    - gcc
    - g++
    - cmake
    - libgmp-dev
    - libboost-dev
    - libboost-filesystem-dev
    - libboost-test-dev
    - python
    - python-pygments
    - libsqlite3-dev
    - libz-dev
    - libedit-dev
    - llvm-8
    - llvm-8-dev
    - llvm-8-tools
    - clang-8
  homebrew:
    update: true
    taps: nasa-sw-vnv/core
    packages:
    - cmake
    - gmp
    - boost
    - llvm@8
    - apron
script:
  - mkdir build
  - cd build
  - if [ $TRAVIS_OS_NAME == linux ]; then cmake -DCMAKE_BUILD_TYPE="Debug" -DLLVM_CONFIG_EXECUTABLE="/usr/lib/llvm-8/bin/llvm-config" ..; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then cmake -DCMAKE_BUILD_TYPE="Debug" -DLLVM_CONFIG_EXECUTABLE="/usr/local/opt/llvm@8/bin/llvm-config" ..; fi
  - make
  - make install
  - make check
env:
  global:
    - MAKEFLAGS="-j2"
